### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mlutfy** [osseed/com.osseed.eventcalendar#100]
Hi @osseed, could you tag a new release, so that the extension officially works on PHP8? (the code was fixed some time ago in master)

We are trying to push for PHP 8 adoption: https://civicrm.org/blog/bgm/php-8-support-civicrm-extensions

If you're busy, I can help with migrating this extension to Gitlab, to help with minor issues like this. Otherwise we will have to remove the "reviewed" status of the extension, so that people do not accidentally install it using the in-app extension browser (it would crash their site).

Thanks!

**Comment by osseed** [comment]
@mlutfy Yes we will do it ASAP.

**Comment by osseed** [comment]
@mlutfy Created new tag 4.2 with php 8 support.

**Comment by mlutfy** [comment]
@osseed Thank you! I updated the blog post.
