### ISSUE TITLE
Issue with generated event links ( wordpress )

### ISSUE THREAD

**Issue by Critter** [osseed/com.osseed.eventcalendar#102]
civicrm ver: 5.63.1
ext ver: 4.2
worpress plugin ver :4.4

When placing the calendar shortcode on a page, the event links are generated based off of that page rather than the civicrm page, which breaks the display of the website.

If the code is on a page 'mytest' links for events are: 

`/mytest/?civiwp=CiviCRM&q=civicrm%2Fevent%2Finfo&id=31`

which basically just outputs the event on a white page with no header/footer or formatting. if the generated link is changed to

`/civicrm/?civiwp=CiviCRM&q=civicrm%2Fevent%2Finfo&id=31`

then the event displays properly with the sites theme.

**Comment by shaneonabike** [comment]
I also found this problem and reported an issue potentially related [here](https://lab.civicrm.org/dev/wordpress/-/issues/149). I made one fix that I will post in a merge request that is require for Frontend links, but that still didn't resolve the issue just yet.

**Comment by osseed** [comment]
@Critter @shaneonabike This is fixed in latest version.
