### ISSUE TITLE
Compatibility with Smarty V3

### ISSUE THREAD

**Issue by themak1985** [osseed/com.osseed.eventcalendar#105]
Not sure when the change to Smarty V3 becomes mandatory with CiviCRM - but when we tested it - this was one of extensions we had an issue with. See error below - for now we are sticking with V2.

![Screenshot 2024-01-10 at 4 12 34 PM](https://github.com/osseed/com.osseed.eventcalendar/assets/28904266/9885786f-2fa8-4592-8f8c-797c056c5a5e)

**Comment by jwgbradford** [comment]
any updates on compatibility with Smarty3? It's now recommended on CiviCRM +5.69 (currently on 5.71 at time of writing), so I'm getting warning messages every time I log in.

**Comment by choess** [comment]
Smarty3 works form me on CiviCRM 5.71 and 5.72 now with release 4.4.

**Comment by jwgbradford** [comment]
Ah - I'm still on EventCalendar 4.3 and CiviCRM isn't showing an available update. I'll upgrade to 5.72.0 over the weekend, and check for 4.4 being available.

**Comment by jwgbradford** [comment]
Amazing - seems to be working perfectly, thanks Osseed
