### ISSUE TITLE
Remove "Powered By CiviCRM ..."

### ISSUE THREAD

**Issue by earlallin** [osseed/com.osseed.eventcalendar#13]
Is there a way to remove this footer message from showing up in the front end? 
I am using WordPress CiviCRM 4.4.11.
![remove_footer](https://cloud.githubusercontent.com/assets/10747849/5979540/91d797ea-a876-11e4-8ac2-ebdc69a37e3c.png)
Never mind this was fixed in master branch . Thanks to christianwach.

**Comment by christianwach** [comment]
This may not help you with 4.4, but I remove the footer in my version of Civi (4.5) by going to *Administer CiviCRM* --> *System Settings* --> *Misc (Undelete, PDFs, Limits, Logging, Captcha, etc.)*, then setting *Display "empowered by CiviCRM"* to 'No'. If 4.4 doesn't have that option, then a bit of CSS should allow you to hide the message.

**Comment by earlallin** [comment]
But that only work on forms. Any ideas on what CSS file I should edit to hide this message? Thanks.
