### ISSUE TITLE
Anonymous Permissions in Drupal with CiviCRM 4.5

### ISSUE THREAD

**Issue by 876solutions** [osseed/com.osseed.eventcalendar#14]
It appears as if there is a permissions issue with event calendar running on v 4.5. Anonymous users are not able to see the /showevents page as this page shows access denied. However authenticated users seem to be able to see it fine. Is there a specific permission setting for this ?

**Comment by sushantpaste** [comment]
Check permission for anonymous user . Give "access CiviCRM " permission to anonymous user.

**Comment by 876solutions** [comment]
Noted but the problem with tht permission is that when the anonymous
user goes to /civicrm/showevents there is a link that gives them access
to the dashboard at /civicrm?reset=1 and in general to this page. This
is not favourable.
Any thoughts on staving that kind of access ?

On 02/24/2015 11:26 PM, sushant wrote:
>
> Check permission for anonymous user . Give "access CiviCRM "
> permission to anonymous user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/osseed/com.osseed.eventcalendar/issues/14#issuecomment-75903662>.
>

-- 
Trevor Forrest
CEO
876 Technology Solutions
Phone: 876-408-4398
Skype: trevorforrest876

**Comment by craigknott** [comment]
It should work if you give anonymous users view event info permission. Make sure you are using the latest version, works for me.
