### ISSUE TITLE
Events disappeared from calendar view when changed any settings.

### ISSUE THREAD

**Issue by tapashdatta** [osseed/com.osseed.eventcalendar#16]
I am on civi 4.6. As a normal install it was working fine until I have changed the settings i.e. change color of events, then events disappeared from the calendar (for public & admin). I am not able to see them no matter what I do. Even uninstall & reinstalling extension does not show changes.

**Comment by madhavimalgaonkar** [comment]
May be try unchecking the show past events fields. The latest release is compatible with laste Civi release.
