### ISSUE TITLE
Is this extension compatible with CiviCRM 4.6? 4.7?

### ISSUE THREAD

**Issue by nganivet** [osseed/com.osseed.eventcalendar#22]

**Comment by lukeberry** [comment]
I have just installed and configured this extension for CiviCRM 4.6.9 on WordPress 4.5.2 

The calendar displays and changes views from Month/Week/Day and also allows you to cycle which month you are viewing but does not display the events on the calendar at all.

Was really hoping that this would still work properly, our organization was looking for this exact functionality.

**Comment by nganivet** [comment]
@lukeberry - we are using this extension on 4.6 with Drupal and it works. Make sure you follow the install instructions - there is a specific paragraph about WordPress at the very bottom.

**Comment by lukeberry** [comment]
@nganivet - Wow, thanks for a response. Didn't expect it seeing that your comment was from March. 

The special note at the bottom of the install instructions is to add the plugin portion of this Civi Extension so it will hook and handle the front-end. That went well as far as I can tell, installed and activated without any errors.

I am not sure where to start to debug the extension so I can use it, it is not logging any errors when viewing the console within the browser and the php log file is not showing anything either. 

May be a query issue, I'll have to check more logs and see if I can find where this is failing.

**Comment by Upperholme** [comment]
Any update on this one? I have a client using this extension with 4.4.x and Wordpress, and is very keen to update to 4.6 or 4.7

**Comment by lukeberry** [comment]
I have not been able to get this to work for my WordPress/CiviCRM site. I am guessing some issue with JavaScipt/jQuery but am unsure.

**Comment by Upperholme** [comment]
The code under the 'develop' branch appears to be compatible with Civi 4.7

**Comment by madhavimalgaonkar** [comment]
The extension is compatible with older and latest release of CiviCRM (4.7.30)
