### ISSUE TITLE
Correct version fullcalendar.js to run

### ISSUE THREAD

**Issue by Upperholme** [osseed/com.osseed.eventcalendar#23]
I've just downloaded the code under the 'develop' branch to test in CiviCRM 4.7 and WP 4.6.1.

The README.txt file indicates that I should download the fullcalendar library from https://github.com/fullcalendar/fullcalendar/releases/tag/v1.6.7

Two questions really:
fullcalendar.js version 1.5.4 looks to be part of this extension's codebase by default. Should I replace that with version 1.6.7?

Looking at https://github.com/fullcalendar/fullcalendar/releases I can see that there a numerous more recent releases of that code. Should we be aiming to use the most recent release, v3.0.1 as I write this, or stick with the suggested 1.6.7?

Many thanks for this extension, and for any response you are able to provide.

**Comment by madhavimalgaonkar** [comment]
Hey @Upperholme, We still using FullCalendar v1.5.4 which works as expected with latest release of extension.
