### ISSUE TITLE
Is anyone having issues with CiviCRM version 4.7.13?

### ISSUE THREAD

**Issue by sqweets** [osseed/com.osseed.eventcalendar#24]
I updated a client site to 4.7.13 from 4.7.11 and the event calendar stopped working.  I am in the process of trying to debug it now but maybe someone else has run into this?

**Comment by bcobin** [comment]
I ended up having to roll back to 4.6 - there's no working solution for 4.7 that I could find. (Both Calendar and FullCalendar have problems in 4.7 that make them unusable.)

Trying now to figure out how to get the extension to show the start times; otherwise, the extension seems to work OK in 4.6.
