### ISSUE TITLE
Wordpress: CiviCRM logo is "Error 404" as of 4.7.27

### ISSUE THREAD

**Issue by twomice** [osseed/com.osseed.eventcalendar#26]
The wordpress plugin references the civicrm logo on the "Event Calendar" button, but it references a file that no longer exists as of CiviCRM 4.7.27 (see https://github.com/osseed/com.osseed.eventcalendar/blob/master/wordpress/wordpress-event-calendar/wordpress-event-calendar.php#L35), thus we get a broken image:

---

![404](https://user-images.githubusercontent.com/759449/35348737-8eb2c42a-00fe-11e8-895b-78e2005a3678.png)
---

In 4.7.27, the logo could be added with something like this:
`$imageBtnURL = $config->resourceBase . 'i/logo_sm.png';`

But you probably want some kind of version sniffing or file existence test, to preserve compatibility with older core versions. Alternatively, you could just embed this image in the WP plugin and avoid the dependency on core.

**Comment by madhavimalgaonkar** [comment]
@twomice This has been fixed in latest version. You can get it here https://github.com/osseed/com.osseed.eventcalendar. Thanks for reporting.

**Comment by twomice** [comment]
Great, thanks!
