### ISSUE TITLE
Install Did Not Create Menus - Calendar gives error.

### ISSUE THREAD

**Issue by themak1985** [osseed/com.osseed.eventcalendar#27]
Not sure if its my own error - recently upgraded to PHP7 and have had some issues. First - the menus do not get added - then when I manually found the Wordpress Menu https://site.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Feventcalendarsettings I get the following error:

`
Warning: strlen() expects parameter 1 to be string, array given in /home/site/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/checkbox.php on line 138
`

When I embed shortcode on wordpress page - I get the following error on that page - the calendar loads but there is no content in the calendar. It also appears at https://website.org/wp-admin/admin.php?page=CiviCRM&q=civicrm%2Fshowevents

`Warning: Invalid argument supplied for foreach() in /home/site/public_html/wp-content/uploads/civicrm/ext/com.osseed.eventcalendar/CRM/Eventcalendar/Page/ShowEvents.php on line 139`

Wordpress 4.9.4 and CiviCRM 4.7.30

**Comment by madhavimalgaonkar** [comment]
@themak1985 This is fixed in the latest version. You can get the version here https://github.com/osseed/com.osseed.eventcalendar
