### ISSUE TITLE
Theme option for Calendar

### ISSUE THREAD

**Issue by 509tyler** [osseed/com.osseed.eventcalendar#3]
Presently extension defaults to the CiviCRM admin theme and not the Public theme. Ideally calendar extension could have the option to use the public theme or the admin theme. Need a work around where one could assign the preferred theme in the Calendar settings admin screen, or a suggestion of how to modify the plugin code to specify a Theme to use.

**Comment by pranav73** [comment]
Closing now as pending from last few years , we will consider this in future development.
