### ISSUE TITLE
Still having issues with Wordpress

### ISSUE THREAD

**Issue by themak1985** [osseed/com.osseed.eventcalendar#34]
Using Wordpress 4.9.4 and Civi 4.7.31

2.1 now creates menus, which is great, but the following error comes up 4x on the Event Calendar Settings (admin side)
`
Warning: strlen() expects parameter 1 to be string, array given in /home5/site/public_html/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/checkbox.php on line 138
`
Otherwise - its working well now!

**Comment by madhavimalgaonkar** [comment]
@themak1985  Fixed in latest version. Thanks for reporting.
