### ISSUE TITLE
Issues with Wordpress

### ISSUE THREAD

**Issue by sarahpwilhelm** [osseed/com.osseed.eventcalendar#45]
Hi,

I'm running EventCalendar v2.3 with Wordpress 4.9.5 and CRM 4.7.31 and there are two issues I cannot resolve: 
1. I get four instances of the error "Warning: strlen() expects parameter 1 to be string, array given in /home/lorenafortx/www/www/wp-content/plugins/civicrm/civicrm/packages/HTML/QuickForm/checkbox.php on line 138" on the Event Calendar Settings page and

2. I cannot publish a public version of the page on the WP side. The button to embed the code exists and appears to work, but nothing shows when viewing the preview or live page.

I have not updated the library because another Issues response stated that the library that comes preinstalled was sufficient. Should I update the library?

Thank you in advance...

**Comment by pranav73** [comment]
Hey Sarah
Sorry to reply you late on this.
Bit confused about version you mention for EventCalendar 2.3 it was released in Aug which was after your comment. So may be you can try upgrading the version. We have checked above issue and those working fine.
Closing this issue for now you can reopen if you still facing any issues
