### ISSUE TITLE
Support multiple calendars?

### ISSUE THREAD

**Issue by twomice** [osseed/com.osseed.eventcalendar#48]
My client is looking to have more than one calendar, e.g., one for "Conference" events and one for "Workshop" and "Staff Training" events. Obviously this would not be a small change and would add a layer of complexity by requiring support for multiple events in the settings page as well as in the shortcode.

Would you consider this a desirable improvement? Would you be interested in contributions toward these features, in the form of sponsorship, contributed code, or otherwise?

**Comment by osseed** [comment]
Thanks.  If your interested in raising PR those will be welcome. If it needs to be urgent we can spend paid time on it.

**Comment by twomice** [comment]
Hi again. My client has finally decided to fund this work, and we've begun work on this PR. Current branch is here: https://github.com/elisseck/com.osseed.eventcalendar/tree/manyCalendars
Looking at the changed code, you can see this will be a pretty big PR. 

Highlights:
- To accommodate multiple calendars, we've moved away from settings and are storing calendar settings in actual civicrm entities (with tables and DAO/BAO classes, etc.)
- The new settings UI supports CRUD operations on calendars, but I'm not yet satisfied with that UI and am trying to re-work it to use civicrm's conventional paradigm of "list all entities in a table with view/edit/delete options for each, and a 'create' button above and below" as seen in most civicrm settings pages, e.g. _Administer > Customize Data and Screens > Relationship Types_
- We're still working out the mechanism for indicating which calendar to display in WP; currently we're just appending "&id=N" to the WP page URL, but that causes some undesirable limitations: 
  - Can't put more than one calendar on a page
  - Can't embed the `id` parameter in the page itself, rather you must put it in the WP menu item URL, which feels clumsy.

Because this is a large PR, and we're hoping to contribute it into the upstream project, your feedback anytime soon would be very helpful to give us some confidence we're not overlooking something that would block such a PR.

Thanks!

**Comment by HeneryH** [comment]
I see some recent code to handle multiple calendars being committed.  Is there a partial implementation of this yet?  The UI shows nothing related yet as far as I can see.

**Comment by osseed** [comment]
@twomice Thanks for PR. 
@HeneryH All changes are in new version with more cleanup and features.
