### ISSUE TITLE
Event Calendar not working in CiviCRM 5.9.1

### ISSUE THREAD

**Issue by mikemazurkiewicz** [osseed/com.osseed.eventcalendar#51]
Hi,

I just updated the CiviCRM version from 5.8 to 5.9.1 and I cannot get the Event Calendar to display on the website and the Event Calendar Settings. When trying to bring up the Settings page, the screen just flashes and returns to the previous page. On the public page, I get:

<div id="crm-container" class="crm-container" lang="en" xml:lang="en"> <style type="text/css" media="screen"> @import url(/components/com_civicrm/civicrm/css/civicrm.css); @import url(/components/com_civicrm/civicrm/css/crm-i.css); @import url(/components/com_civicrm/civicrm/bower_components/font-awesome/css/font-awesome.min.css); </style> <div class="messages status no-popup"> <i class="crm-i fa-exclamation-triangle crm-i-red"></i> <span class="status-fatal">Sorry, due to an error, we are unable to fulfill your request at the moment. You may want to contact your administrator or service provider with more details about what action you were performing when this occurred.</span> <div class="crm-section crm-error-message">You do not have permission to access this page.</div> <p><a href="https://www.rbsportsboosters.com/" title="Main Menu">Return to home page.</a></p> </div> </div> <script language="JavaScript"> function toggle( element ) { var parent = element.parentNode; var className = parent.className; if ( className == 'crm-accordion-wrapper collapsed crm-fatal-error-details-block') { parent.className = 'crm-accordion-wrapper crm-fatal-error-details-block'; } else { parent.className = 'crm-accordion-wrapper collapsed crm-fatal-error-details-block'; } } </script>

An error has occurred while processing your request.

You may not be able to visit this page because of:

    an out-of-date bookmark/favourite
    a mistyped address
    a search engine that has an out-of-date listing for this site
    you have no access to this page

Any suggestions would be appreciated.
Mike

**Comment by madhavimalgaonkar** [comment]
Hey @mikemazurkiewicz glad that you reached out!
You need to clear cache and rebuild the menus as you upgraded CiviCRM. You can rebuild CiviCRM menus For joomla using 
http://DOMAIN/administrator/?option=com_civicrm&task=civicrm/menu/rebuild
