### ISSUE TITLE
Event Calendar not working in CiviCRM 5.10.1

### ISSUE THREAD

**Issue by rupertraphael** [osseed/com.osseed.eventcalendar#52]
Just upgraded from CiviCRM 4.6.8 to 5.10.1 and I can't see my events in the calendar while the Event Calendar Settings page returns a blank page.

Any workarounds are much appreciated.

**Comment by pranav45** [comment]
Hey @rupertraphael
You need to clear cache and rebuild the menus as you upgraded CiviCRM. Here is the link to clear cache http://DOMAIN//civicrm/admin/setting/updateConfigBackend?reset=1 and rebuild menu http://DOMAIN/civicrm/menu/rebuild
btw are you using drupal as CMS ?  then you need to add [jqueryupdate](https://www.drupal.org/project/jquery_update) module.

**Comment by rupertraphael** [comment]
Hi @pranav45, I've tried clearing the cache, rebuilding the menus, and, actually, I already have the jqueryupdate module installed but now, both pages, the events calendar page and event calendar settings page, return a blank page. 

By the way, I am not getting any errors in the browser's console nor in the Civi logs.

<img width="1433" alt="Calendar Events Page" src="https://user-images.githubusercontent.com/19609578/54762375-9c033680-4bb9-11e9-8bbd-e60ad753ae44.png">
<img width="1436" alt="Event Calendar Settings Page" src="https://user-images.githubusercontent.com/19609578/54762376-9c9bcd00-4bb9-11e9-848c-76cf9ddeaf63.png">
<img width="1367" alt="Screen Shot 2019-03-21 at 9 14 28 AM" src="https://user-images.githubusercontent.com/19609578/54762444-c523c700-4bb9-11e9-9c9f-19b082990cc9.png">


Anymore ideas?

**Comment by rupertraphael** [comment]
Changing the jQuery version to 1.10 removed the errors and the calendar is now displaying but without any events while the settings page is still blank.

<img width="1396" alt="Blank Calendar on event calendar page" src="https://user-images.githubusercontent.com/19609578/54771082-2d7aa480-4bca-11e9-831f-13bb4b8ce6c5.png">

**Comment by osseed** [comment]
@rupertraphael Can you confirm if your event settings are correct like you enabled event types and other settings at civicrm/eventcalendarsettings. Also your events are public right ? If you need help you can send us email on hello@osseed.com with details we can check and help you to sort this.

**Comment by rupertraphael** [comment]
@pranav45 and @osseed, I have solved my problems by redoing the whole upgrade process. Thank you so much for reaching out. Cheers!
