### ISSUE TITLE
How to install fullcalender for drupal?

### ISSUE THREAD

**Issue by tapashdatta** [osseed/com.osseed.eventcalendar#53]
I was trying to install but it seems the extension is not able to get the library. Is there a tutorial how to enable fullcalender library please? Thanks

**Comment by pranav45** [comment]
The library is already added into the extension so there is no need to add library externally. Just download the latest extension release from [here](https://github.com/osseed/com.osseed.eventcalendar/tree/v.2.4) we will update the readme file in next release. if you still facing any issue, please latest know.

**Comment by tapashdatta** [comment]
Thanks Pranav. I have figured that jQuery library was not set correctly. And it seems the extension likes jQv1.7+.  Perhaps worth mentioning in the Readme.

**Comment by pranav45** [comment]
Thanks @tapashdatta for pointing this out. We will fix the README in next release.
