### ISSUE TITLE
Support booking multiple event?

### ISSUE THREAD

**Issue by tapashdatta** [osseed/com.osseed.eventcalendar#54]
Hi 
My client would like to book multiple events from the calender like sagenda.com. Is it something achievable? thanks

**Comment by pranav45** [comment]
Hey, @tapashdatta currently we don't have any plans for doing this, but it seems interesting. We will get back to you after spending some time in this. Definitely, this is achievable but needs extra effort.

You can contact at hello@osseed.com if you are interested to discuss on this.

**Comment by pranav45** [comment]
@tapashdatta Closing this issue as we discuss in email.
