### ISSUE TITLE
Setting hex color to event calendar

### ISSUE THREAD

**Issue by kalexisb** [osseed/com.osseed.eventcalendar#56]
I am trying to set hex color to a CiviCRM event calendar by events types.  

I would also like to change the font color of the "text" - in the hyperlink to the event to make it readable with whatever hex color that is chosen.

Using latest civi 5.x (5.12)

**Comment by osseed** [comment]
@kalexisb Currently  we have only settings for background hex color per event type, there is no functionality to provide color to title link. This is very specific requirement you can reach us on hello@osseed.com and we can help you.

**Comment by kalexisb** [comment]
Thank you I will do that.

**Comment by osseed** [comment]
@kalexisb Hope the recent commits fix your issue. Closing this reopen if needed.
