### ISSUE TITLE
Events not showing up

### ISSUE THREAD

**Issue by kelizoliva** [osseed/com.osseed.eventcalendar#57]
Testing out this extension - None of the events in the system are showing up on the calendar. This is on CiviCRM 5.13.5.. Nothing is coming up in the logs.

**Comment by hbartel** [comment]
In CiviCRM go to Administer menu > CiviEvent >Event Calendar Settings.
Check all the check boxes at the bottom by the different types of events. (conference, exhibition, meeting)
Checking the box displays that type of event on the calendar.
The settings page is not clear that you need to check these boxes to show the events.

**Comment by osseed** [comment]
@hbartel Thanks for adding notes here! 
@kelizoliva Closing this re-open if you still have issue.
