### ISSUE TITLE
Can't get events to show on site

### ISSUE THREAD

**Issue by Wyntery** [osseed/com.osseed.eventcalendar#59]
Wordpress 5.2.2 and CiviCRM 5.14.1 - have added CiviCRM Events Calendar and EventCalendar. I followed these instructions: https://civicrm.stackexchange.com/questions/22680/how-to-use-event-calendar-extension-with-civievents 
Events show in the Civi Event Calendar but not on the EventCalendar at the front end. What am I missing? I have very basic skills. So basic instruction would be great!
Thanks

**Comment by pranav45** [comment]
@Wyntery As you mentioned in above comment have checked that issue and have come with one solution for displaying event calendar on wordpress front end you need to follow these steps:
1)After installing event calendar extension you need to copy the folder "yourextensiondirectory/com.osseed.eventcalendar/wordpress/wordpress-event-calendar" to "wordpressdirectory/wp-content/plugins/" and activate the plugin which will add CiviCRM frontend type for Event Calendar.
2)Then create wordpress page and add shortcode with data like [event_calendar component="event-calendar"] then publish that page and check the calendar event will be appear on front page.Also make sure your events are public.

**Comment by Wyntery** [comment]
Thanks @pranav45 I have done this, but the calendar doesn't show. this is the result I get: http://146.66.90.42/~myfitn02/sessions/ 
What am I doing wrong?

**Comment by pranav45** [comment]
@Wyntery Not sure there must be some jquery issue as in console I can see error related to jquery. If you want we can help you to reslove this you can send email with details at hello@osseed.com

**Comment by pranav45** [comment]
@Wyntery Closing this issue as we discuss in email.
