### ISSUE TITLE
Joomla Calendar Display Issues

### ISSUE THREAD

**Issue by acmfox** [osseed/com.osseed.eventcalendar#6]
Installed on Joomla 2.5/civicrm4.3; Event Calendar works fine in civicrm admin section, but when I try to create a menu item and reach it via the public site I have two problems:
1. not logged in: get permissions violation (I did set show events to 'public' in settings)
2. logged in: get civi event event listings, which is not a calendar format, displaying a table of all events and registrants.

**Comment by madhavimalgaonkar** [comment]
The latest version of extension is compatible with latest Joomla release (3.8.6).
