### ISSUE TITLE
What are requirements for this to work with Drupal 8

### ISSUE THREAD

**Issue by petednz** [osseed/com.osseed.eventcalendar#60]
There is no D8 release for jquery_update because it is now in core.
I have enabled the extension and visited civicrm/eventcalendarsettings but looks like the default config on that page should mean I see events at civicrm/showevents but see nothing

**Comment by osseed** [comment]
Sorry to reply you late on this.

We haven't check this on Drupal 8 yet we will releasing it soon.

**Comment by petednz** [comment]
great - keen to see what you get working

**Comment by pranav45** [comment]
@petednz  Here is the link for Drupal 8 support https://github.com/osseed/com.osseed.eventcalendar/releases/tag/3.0 please check.

**Comment by jusfreeman** [comment]
tag/3.0 **does not work** with Drupal 7
tag/2.4 **does work** with Drupal 7

**Comment by pranav45** [comment]
@jusfreeman You are right have created separate version for Drupal 8 & also its mention in readme file.

**Comment by edward-peters** [comment]
@petednz Did you get this working. I have installed v3.0 for D8, the settings page is fine, but I see nothing output at civicrm/showevents

**Comment by petednz** [comment]
@edward-peters probably best to open new issue - did you mean 3.0 or 3.2?
@pranav45 you said you had updated readme file. i see no mention of which version to use for D7 v D8 at https://github.com/osseed/com.osseed.eventcalendar/blob/master/README.txt

**Comment by edward-peters** [comment]
@petednz Thanks so much. I have now installed 3.2 but it still does not work so I will open a new issue as you suggest.
