### ISSUE TITLE
Calendar will not show in WordPress

### ISSUE THREAD

**Issue by KilakwaBT** [osseed/com.osseed.eventcalendar#63]
Hi, I have installed the extension & the WordPress plugin and can configure the settings in CiviCRM. When I go to view the Calendar I get the title I configured and if I include the event type filter that drop down shows but I do not get the Calendar with events. This install is CiviCRM 5.16.3 w/WordPress 5.2.4 and the most recent version of the extension.

**Comment by pranav45** [comment]
@KilakwaBT  The current version of eventcalendar 3.0 is only supported for Drupal8 & have already mention that in readme file. You can use eventcalendar version 2.4 with latest version of wordpress & civicrm.
