### ISSUE TITLE
Event Calendar, Version 3.0 only works with Drupal 8, but is supposed to be CMS Compatibility: CiviCRM Native (all CMS)

### ISSUE THREAD

**Issue by jusfreeman** [osseed/com.osseed.eventcalendar#65]
Continuing the discussion from https://github.com/osseed/com.osseed.eventcalendar/issues/60

Version 3.0 only works with Drupal 8, but is supposed to be CMS Compatibility: CiviCRM Native (all CMS). See https://civicrm.org/extensions/event-calendar-extension

WordPress, Drupal 7, Joomla etc. CiviCRM sites will receive an "in-place" upgrade notice. When a Drupal 7 site updates to Event Calendar, Version 3.0 - **it will no longer work**.

It's not really feasible to have the latest version specific to Drupal 8 and version prior works with Drupal 7. And it's not really sufficient to say version 3.0 only works with Drupal 8 in a README file, that no one reads - until something is not working.

![chrome_I5OXufGWWh](https://user-images.githubusercontent.com/10555210/68901564-430c9200-078a-11ea-8a93-2b6a457d0a55.png)

Agileware Ref: CIVICRM-1369

**Comment by pranav45** [comment]
@jusfreeman  Have Fixed that CMS compatibility issue under eventcalendar latest release visit URL:https://github.com/osseed/com.osseed.eventcalendar/releases/tag/3.1

**Comment by jusfreeman** [comment]
@pranav45 thanks for that, I am sure this will help avoid issues for other users too in future. Good job!
