### ISSUE TITLE
Add setting for week start day

### ISSUE THREAD

**Issue by em-piguet** [osseed/com.osseed.eventcalendar#67]
If possible, we would like to have the week start on monday instead of sunday as a setting (it already exist in core civicrm date settings.

**Comment by sushantpaste** [comment]
@em-piguet that would be a nice option. We will check if we can add in next release.

**Comment by pranav45** [comment]
@em-piguet Have added setting for week start day functionality under eventcalendar latest release visit URL: https://github.com/osseed/com.osseed.eventcalendar/releases/tag/3.2
