### ISSUE TITLE
Improvement: Show event only the days rather than whole length.

### ISSUE THREAD

**Issue by tapashdatta** [osseed/com.osseed.eventcalendar#69]
It's a feature improvement rather than an issue. We have an event that runs every sunday for a whole year. When the start & end date is selected, the event shows everyday throughout the year, which is not correct. I think an option to set the interval to show event would be more realistic.

**Comment by pranav45** [comment]
@tapashdatta  Civicrm provides recurring event functionality.Refer this for event repeat functionality https://docs.civicrm.org/user/en/latest/events/repeating-events/. Also have added setting under event calendar setting page,where you need to display only recurring event.
