### ISSUE TITLE
The calendar is not displaying

### ISSUE THREAD

**Issue by xpdientUK** [osseed/com.osseed.eventcalendar#70]
Hi there

Using 5.21.0 and v 3.2 Calendar. Drupal up to date.

The calendar is not displaying.

**Comment by pranav45** [comment]
@xpdientUK Have checked the eventcalendar extension with above civicrm version & calendar working for me.Please check readme https://github.com/osseed/com.osseed.eventcalendar/blob/master/README.txt  follow the steps for extension setup.
