### ISSUE TITLE
Show event calendar in frontpage

### ISSUE THREAD

**Issue by abdelkafi-med** [osseed/com.osseed.eventcalendar#72]
Hi,
I'm using Event Calendar 3.2 on CiviCRM 5.22.1
I want to show calendar of current events on a page open for public.

I understand that i have to use the shortcode [event_calendar] but I can't find any documentation about attributes.

Without attributes, the shortcode throw an error.
If I add anything, nothing happen ou shown on the page.
[https://horizontunisia.org/test-calendrier-page](https://horizontunisia.org/test-calendrier-page)
 in this example, i add " id=1 " in the shortcode.

So, what are the attributes to use with the shortcode ?

Thanks.

**Comment by elliottmart** [comment]
I would like to know how to use it with a shortcode too please.

**Comment by pranav45** [comment]
@abdelkafi-med @elliottmart  For displaying event calendar on WordPress front-end you need to follow these steps:
1)After installing the event calendar extension you need to copy the folder "yourextensiondirectory/com.osseed.eventcalendar/wordpress/wordpress-event-calendar" to "wordpressdirectory/wp-content/plugins/" and activate the plugin which will add CiviCRM frontend type for Event Calendar.
2)Then create a WordPress page and add shortcode with data like [event_calendar component="event-calendar"] then publish that page and check the calendar event will appear on the front page. Also, make sure your events are public.
3)Clear cache from CiviCRM & WordPress once & check calendar will appear on the front page.

If you still have any query after that regarding eventcalendar then drop us mail on hello@osseed.com
