### ISSUE TITLE
No output for Show Calendar in Drupal 8 using 3.2

### ISSUE THREAD

**Issue by edward-peters** [osseed/com.osseed.eventcalendar#73]
I installed the Jan 29 release 3.2 for Drupal 8, and configured everything but there is no output at all at /civicrm/showevents. I have cleared cache numerous times.
Am I missing something or is there a bug with this release?

**Comment by osseed** [comment]
@edward-peters We will check this issue and get back to ASAP

**Comment by edward-peters** [comment]
@osseed It seems ok after all! When I sent to showevents today there was output. I cannot explain why it did not yesteday, as I cleared cache multiple times. Anyhow, all ok, and apologies for bothering you unnecessarily.
