### ISSUE TITLE
Get 'Error loading calendar, try refreshing...' after installing

### ISSUE THREAD

**Issue by clarkac1** [osseed/com.osseed.eventcalendar#76]
Using CiviCRM 5.26.2, Drupal 7 and JQuery Update set at 1.4 I cannot load the events calendar.  I have first updated the settings which have saved OK but when I go to display the events calendar I get the above message.  There are only a couple of events, one in the past and one in the future.   The extension is at version 3.3. I have tried clearing both Drupal & Civi caches, but always get the above error.

**Comment by osseed** [comment]
@clarkac1 Can you send more details screenshot or is there any error in console?

**Comment by clarkac1** [comment]
Here's a screen shot. nothing in ConfigAndLog
![screenshot_20200723_082155](https://user-images.githubusercontent.com/5676413/88261301-ec166f80-ccbd-11ea-9df6-a5fd4cbfe9cd.png)

**Comment by osseed** [comment]
@clarkac1 It seems to be issue with jquery update module please check upgrading jquery update to latest releases or set jquery version above 1.4

**Comment by clarkac1** [comment]
I set it to 1.12 - it was previously at 1.4 (Drupal) which I guess is the builtin Drupal level.  However the problem remains the same , after clearing both Drupal and CiviCRM caches.

**Comment by osseed** [comment]
@clarkac1 We tried with same config and it works well. It seems to be issue with jquery version.

If you send some details on hello@osseed.com we can help you.

**Comment by clarkac1** [comment]
What sort of details do you need?  Happy to send anything you require

**Comment by osseed** [comment]
@clarkac1 Send us admin details of your site first. We can check and let you know if anything needed.

**Comment by osseed** [comment]
@clarkac1 Let us know if you still need help? closing this issue for now.
