### ISSUE TITLE
Uncaught TypeError: $(...).live

### ISSUE THREAD

**Issue by kdflint** [osseed/com.osseed.eventcalendar#81]
Hello. I am running Event Calendar 3.3 / CiviCRM 5.31.1 / Drupal 7.75 / jQuery 1.10

Attempting to show my calendar at Events > Show Events Calendar I get the name of the calendar with an otherwise empty output. This error shows in browser console.

I am able to interact with the Event Calendar Settings screen, seemingly without issue.

Suggestions for next steps?

```
15:24:37.549 Uncaught TypeError: $(...).live is not a function
    Ember 9
        attach
        attachBehaviors
        each
        attachBehaviors
        <anonymous>
        c
        fireWith
        ready
        q
js_jdjs8WjatBdwFZcUCGk5PpOiHCyK4po1t6VVr20iHgk.js:31:28
    Ember 9
```

**Comment by kdflint** [comment]
Closing, no response.

**Comment by pranav45** [comment]
@kdflint as you mentioned drupal & civicrm version have checked the event calendar version 3.3 & it works fine for me.Have you added [jquery](https://www.drupal.org/project/jquery_update ) module with required configuration?As we mentioned under readme file.
