### ISSUE TITLE
Events showing graphically longer than their set times. Behavior of "Show End Dates"?

### ISSUE THREAD

**Issue by HeneryH** [osseed/com.osseed.eventcalendar#82]
I am using an event calendar do show a series of asset times slots available for reservation.

My question/issue is about the behavior of the "Show End Dates" flag.

I was expecting that flag to only impact the visibility of the end time on the graphic.

But is impacts the overall graphic look, more than just the display of the end time.  When that flag is ON then I get proper display of my 50 minute slots.

See these two images of the calendar.  The ONLY difference between them is the "Display End Date" setting.

Is this the expected behavior?

[https://i.imgur.com/t7dMBVx.png](url)
[https://i.imgur.com/BjFndWZ.png](url)

**Comment by pranav45** [comment]
@HeneryH Have gone through your scenario & updated the end time functionality which will be displayed as per show end date settings & that is expected behaviour. Please check the new release of the [eventcalendar](https://github.com/osseed/com.osseed.eventcalendar/releases/tag/4.1) extension.
