### ISSUE TITLE
Version 4.0 front-end view does not work on Joomla

### ISSUE THREAD

**Issue by webmaster-cses-org-uk** [osseed/com.osseed.eventcalendar#83]
Version 4.0 front-end gives a permission error on Joomla.

Issue appears to be related to joomla/EventCalendar/tmpl/default.xml:
&lt;field name="task" type="hidden" default="civicrm/showevents?id=" /&gt;

'id' needs to be a separate parameter (cannot chain URL parameters in single field, especially as it would need to be & not ?, but in any case don't think this is legal in Joomla).

Suggestion:
&lt;field name="task" type="hidden" default="civicrm/showevents" /&gt;
&lt;field name="reset" type="hidden" size="5" default="1"  /&gt;
&lt;field name="id" type="hidden" default="1"  /&gt;
(setting id as required)

NOTE: need to update documentation to tell users to add their settings ID to this file after copying to Joomla components directory (or make this a drop-down field in Joomla menu configuration), AND need to add ID to url in CiviCRM back-end menu.

**Comment by osseed** [comment]
@webmaster-cses-org-uk We will check this and get back to you. Which version of Joomla and CiviCRM you'r using?

**Comment by webmaster-cses-org-uk** [comment]
Thanks :)

Joomla = 3.9.8
CiviCRM = 5.33.1

**Comment by pranav45** [comment]
@webmaster-cses-org-uk Thanks for the solution. As per your suggestion, we have fixed the issue and committed under the master branch. We will add these fixes under the new release.
