### ISSUE TITLE
Edit Calendar page in Wordpress 'jQuery is not defined'

### ISSUE THREAD

**Issue by 2ontheriver** [osseed/com.osseed.eventcalendar#86]
I have Wordpress 5.7 running with the Astra theme. I have CiviCRM 5.35.1

I installed the calendar without a problem. I then used the shortcode, as described in the readme, on a new page to display the calendar on the front end. When viewing this page on the front end, it displays correctly.

However when I then tried to edit the page containing the calendar in the wordpress admin, the page is no longer working as expected, there were may javascript errors the first being 'jQuery is not defined'. (I include a screenshot at the bottom)

I have tried to access the edit page multiple times, and each time I got the same result. 
I tried editing other pages which are working normally. 
I created a new page which could be edited, but then as soon as I added the shortcode for the calendar I got the issue mentioned above when I attempted to edit it.

![Calendar Issue](https://user-images.githubusercontent.com/19410828/112131736-c382a480-8bc1-11eb-8507-f117d1669216.jpg)

**Comment by osseed** [comment]
@2ontheriver This is fixed in https://github.com/osseed/com.osseed.eventcalendar/commits/master check latest commit it will be part of next release.
