### ISSUE TITLE
How to use it with drupal

### ISSUE THREAD

**Issue by ugintl** [osseed/com.osseed.eventcalendar#87]
I have just installed civicrm to drupal 9 using composer. How can I use this extension with drupal?

**Comment by pranav45** [comment]
@ugintl download the [extension](https://github.com/osseed/com.osseed.eventcalendar). Move the downloaded extension to your extensions folder.After that goto `[site:url]/civicrm/admin/extensions&reset=1`  -- install the extension.Once installation is done follow the below steps
1. Click Administrator->CiviEvent->Event Calendar Settings menu (civicrm/admin/event-calendar) -- change the setting if required.
2. Now you can add multiple calendar with specific settings & preview event data as per settings on calendar.
3. Click Events->Show Events menu (civicrm/showevents) -- to view global Event Calendar with Events as per setting
