### ISSUE TITLE
The full title of the event is not displayed in the calendar

### ISSUE THREAD

**Issue by Guydn** [osseed/com.osseed.eventcalendar#89]
See an example Wordpress
![RO question on event display](https://user-images.githubusercontent.com/35797460/145866088-e5a278fd-c8be-4595-9864-3a76f8956687.png)

Is there a way to change the presentation so that the size of the event rectangle or tile fits the length of the text (as it is in Event Organizer of WordPress)

**Comment by Upperholme** [comment]
I've just installed this extension (which reports as version 4.2) - for which many thanks - on a Drupal 7 site running Civi 5.68.1 on PHP 7.4 and seeing this odd behaviour with event titles not being fully displayed. This may well be down to running old versions of Drupal and PHP (and I'm working on updating this site to D10 and PHP 8.x). but wondered if there was something I could do to improve display?

**Comment by Guydn** [comment]
I did not find the solution. I finally decided to use a Wordpress extension FullCalendar and a link between CiviCRM and this extension.
