### ISSUE TITLE
Page edition in back office wordpress is broken

### ISSUE THREAD

**Issue by wyde22** [osseed/com.osseed.eventcalendar#90]
Hi,

I have this version of civicrm extension : 4.1 and in the WordPress page edition with a event calendar shortcode, i have a white page

![Capture_page_blanche](https://user-images.githubusercontent.com/13589372/151781415-9d93a940-2152-4c49-9aaa-65559fdc6de4.JPG)

here an error in the console of browser

![Capture_page_blanche_2](https://user-images.githubusercontent.com/13589372/151781600-a422b11c-e774-4e1e-8111-a0d0a1e6d057.JPG)

I can't edit this page

Have you got a solution for this problem ?

my installation :
- WP 5.8.3
- Wordpress Event Calendar [(https://fr.wordpress.org/plugins/wordpress-event-calendar/)](https://fr.wordpress.org/plugins/wordpress-event-calendar/)

Thanks

**Comment by osseed** [comment]
@wyde22 try installing classic-editor plugin.
