### ISSUE TITLE
PHP error thrown by /civicrm/showevents

### ISSUE THREAD

**Issue by edward-peters** [osseed/com.osseed.eventcalendar#91]
When I go to https://www.scl.org.uk/civicrm/showevents, there is a PHP error (it was working ok before):

Error: Class 'CRM_EventCalendar_Page_ShowEvents' not found in CRM_Core_Invoke::runItem() (line 298 of /home/scluk/public_html/sclukd8/vendor/civicrm/civicrm-core/CRM/Core/Invoke.php)

Would you have any clue what might be causing this and how I might fix it? I did a Google search but there are no results on that error.

Thank you!

**Comment by osseed** [comment]
@edward-peters Can you please let us know the version of CiviCRM and extension you are using ?

**Comment by edward-peters** [comment]
Apologies! 
It is version 4.1 of the extension, which I believe is the most recent?
The site is running CiviCRM 5.42.1

**Comment by osseed** [comment]
@edward-peters We have checked same version of extension and CiviCRM on Drupal CMS and it's working fine. Can you send more info specific PHP version ? May be try clearing cache once.

**Comment by edward-peters** [comment]
In case anyone has a similar problem, it seems that the issue was caused by an update of the code base which did not respect the change of folder name from 'Eventcalendar' to 'EventCalendar'.
