### ISSUE TITLE
Calendar do not translate to french

### ISSUE THREAD

**Issue by syxys1** [osseed/com.osseed.eventcalendar#96]
Hello,

I have installed Event Calendar v4.1 on CiviCRM v5.50.1 running on Wordpress v6.0 .  CiviCRM language setting is français (Canada) although I have tried français (France).  Wordpress language is also français du Canada.

I have also installed the Localization Update (l10n) extension.  All traductions files are present in com.osseed.eventcalendar/l10n/fr_CA/LC_MESSAGES and .../fr_FR/LC_MESSAGES.

Other extension having their traductions files present translate to french but Event Calendar won't. 

Given that I need to publish the calendar to a public Wordpress site, it would be much appreciate that it speak the same language.

Where should I look first for debugging?

Regards

**Comment by fossil-free** [comment]
Did you check whether there even exists a french translation for this extension?

German translation works fine.

**Comment by osseed** [comment]
Fixed in latest version
