### ISSUE TITLE
locale ignored for date & time

### ISSUE THREAD

**Issue by fossil-free** [osseed/com.osseed.eventcalendar#98]
Thanks for the great extension!

It appears to ignore server locale & civicrm locale settings though. All text is translated all right, but the date, day of week & time formats are still in US English, no matter any of the settings in civicrm core.

My skills don't suffice to check the original files on whether there is a locale check implemented at all. Can somebody check?

**Comment by osseed** [comment]
@fossil-free Here is the fix https://github.com/osseed/com.osseed.eventcalendar/commit/19e4cee9355d9f78cb04bdcd112859c37ed7b80d it will be part of next version.

**Comment by fossil-free** [comment]
I just checked 4.2 (released in 01/23), unfortunately your updated code here from 12/22 wasn't included. Could you compile a 4.3 version?
(4.2 is still noted as beta version in the CiviCRM extensions directory, is this intended?)
