### ISSUE TITLE
Drupal Install - Error Loading Calendar, try Refreshing

### ISSUE THREAD

**Issue by BrownsIT** [osseed/com.osseed.eventcalendar#99]
Getting the above error after an installation of event calendar on Drupal using CiviCRM 5.52.2.

I have setup a calendar view but getting the error when trying to preview or when accessing through Events>Show Events Calendar menu option.

**Comment by osseed** [comment]
@BrownsIT May be try clearing cache . also check if fullcalendar.js is loading or not.
